$axure.loadCurrentPage({
  "url":"cici-wap.html",
  "generationDate":new Date(1456808408739.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cfdd19e32cbc4308a358be496e5e1288",
    "type":"Axure:Page",
    "name":"cici-wap",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0bb629e5714a4496be9c515531f9634a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":750,
              "height":2850}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdcda72638db4e9b9f9e1d007af8ede0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":750,
                  "height":2850}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-wap/u0.jpg"}},
{
          "id":"67ab84bb19284ff5824470a3f9130c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09d20e5c7dc46e4becb67311566c21d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-wap/u2.png"}},
{
          "id":"7a67c2b101d846c99c2839f989e8e01e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":93,
              "y":56},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3dd8d4b8c474189aeba55d223a11b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":56},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3704c11b0654954ae58dd9de8f89c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":56},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c762120529ad406aa8414b983dd12982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":56},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36d15e48ddc54e7c848dd3ca82e072dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":540,
              "y":56},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90966ae6b14049ebb09c21c0b984133a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":540,
                  "y":56},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"29cd78ca4ac249bc829191ce5c1df380",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":557,
              "y":67},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e962e139ea3248b2a2ced8c87faed606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":557,
                  "y":67},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2a9b19067454ee4838c455e470b9794",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":620,
              "y":410},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06e3bf0c0ca14c32bfd76bf7d124b3e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":620,
                  "y":410},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"7c87743b20474629a1600b825eb0f6ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":637,
              "y":421},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04ddec5e313f401983994dea0815073e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":637,
                  "y":421},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e69a31b53d944410afa6b44230a8e0b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":680},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac9eedbfbd4401bb2c641cc86b3b37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":680},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"13b2b5f3724b4fcb813847ca3dd4cfab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":467,
              "y":691},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd9efdd5a3b54e74a2ea699453f02ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":467,
                  "y":691},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f745ba1aaf6a452ea7a3ca5f931f72e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":90},
            "size":{
              "width":378,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7810c68cd5834e5d961636ea3b403da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":90},
                "size":{
                  "width":378,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b923e1758d44ca99c5a2548a993b1d6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1360},
            "size":{
              "width":840,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cici-wap/u22_line.png"}},
{
          "id":"e94820e681c5484cac71e379c9e07a0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":1310},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90814a264ce5407ba4fc63b78b634a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":771,
                  "y":1310},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffccd74d892943f9975ea51c144924bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":1388},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94885ac0e1534b3fb3f484e6b878ab32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":771,
                  "y":1388},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46cc7e4b5c0e427d8bba698d03151c0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":190},
            "size":{
              "width":348,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878f2ddb1e1f41fcbcfc7299e2972b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":190},
                "size":{
                  "width":348,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20b3d5d8cafb46bca982b55a93e49934",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30,
              "y":1388},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0527c26cdae465bac7cf885106b58b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30,
                  "y":1388},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"b6d9aa714fc94077af0ccb25adb53d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":47,
              "y":1399},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2698d84d0f345b0a41f11be98a86e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":47,
                  "y":1399},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d44a76f857bc4579b55bcf507b387be7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":467,
              "y":1388},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6448db185e2145299d3387f878db5ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":467,
                  "y":1388},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"6282d05fa2364713bb4a73c1274207b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":484,
              "y":1399},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c9ed62eeb364eec92cceb854965f99f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":484,
                  "y":1399},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aa4d0d7dc264a06809871ea1c35da8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":1680},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61cf3a19041c4ceb9006e31a9958a3bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":170,
                  "y":1680},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"79787fac6c1f4be486e83d894d5185e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":187,
              "y":1691},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a9de68d1d3451c92c35eaf724eec5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":1691},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff2e931a9a514d9d80ab5fc5dce49d32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":460,
              "y":1810},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e14d9000eb6948d6903800b1cb953f47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":460,
                  "y":1810},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"44c3929271f9466ab21dd04ac832bf75",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":477,
              "y":1821},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f30df6773af4650b5f8cac5c4109b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":477,
                  "y":1821},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b9a4c9ea3fc4b1c8c89f7d5f653823c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":680,
              "y":2200},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb23fbf8924420b86e3f436c039b5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":680,
                  "y":2200},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"a73971df86ba4fb1b06063b2a695ecb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":697,
              "y":2211},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b40acf3e7ae43dfb0f3844ac71b7a3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":697,
                  "y":2211},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d47c3f99e764eafa707ff177b6658c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":800,
              "y":324},
            "size":{
              "width":157,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9b45f02a9f436597b6554f951b1643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":800,
                  "y":324},
                "size":{
                  "width":157,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34bd43d8b2c24e54b2b6674d075dc960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":2217},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e969d9e811c646c8804b4cc4b68151bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":2217},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0bb629e5714a4496be9c515531f9634a":{
      "scriptId":"u0"},
    "cdcda72638db4e9b9f9e1d007af8ede0":{
      "scriptId":"u1"},
    "67ab84bb19284ff5824470a3f9130c0b":{
      "scriptId":"u2"},
    "d09d20e5c7dc46e4becb67311566c21d":{
      "scriptId":"u3"},
    "7a67c2b101d846c99c2839f989e8e01e":{
      "scriptId":"u4"},
    "c3dd8d4b8c474189aeba55d223a11b51":{
      "scriptId":"u5"},
    "b3704c11b0654954ae58dd9de8f89c89":{
      "scriptId":"u6"},
    "c762120529ad406aa8414b983dd12982":{
      "scriptId":"u7"},
    "36d15e48ddc54e7c848dd3ca82e072dc":{
      "scriptId":"u8"},
    "90966ae6b14049ebb09c21c0b984133a":{
      "scriptId":"u9"},
    "29cd78ca4ac249bc829191ce5c1df380":{
      "scriptId":"u10"},
    "e962e139ea3248b2a2ced8c87faed606":{
      "scriptId":"u11"},
    "c2a9b19067454ee4838c455e470b9794":{
      "scriptId":"u12"},
    "06e3bf0c0ca14c32bfd76bf7d124b3e0":{
      "scriptId":"u13"},
    "7c87743b20474629a1600b825eb0f6ab":{
      "scriptId":"u14"},
    "04ddec5e313f401983994dea0815073e":{
      "scriptId":"u15"},
    "e69a31b53d944410afa6b44230a8e0b6":{
      "scriptId":"u16"},
    "eac9eedbfbd4401bb2c641cc86b3b37f":{
      "scriptId":"u17"},
    "13b2b5f3724b4fcb813847ca3dd4cfab":{
      "scriptId":"u18"},
    "cd9efdd5a3b54e74a2ea699453f02ca2":{
      "scriptId":"u19"},
    "f745ba1aaf6a452ea7a3ca5f931f72e9":{
      "scriptId":"u20"},
    "7810c68cd5834e5d961636ea3b403da4":{
      "scriptId":"u21"},
    "0b923e1758d44ca99c5a2548a993b1d6":{
      "scriptId":"u22"},
    "e94820e681c5484cac71e379c9e07a0b":{
      "scriptId":"u23"},
    "90814a264ce5407ba4fc63b78b634a88":{
      "scriptId":"u24"},
    "ffccd74d892943f9975ea51c144924bb":{
      "scriptId":"u25"},
    "94885ac0e1534b3fb3f484e6b878ab32":{
      "scriptId":"u26"},
    "46cc7e4b5c0e427d8bba698d03151c0a":{
      "scriptId":"u27"},
    "878f2ddb1e1f41fcbcfc7299e2972b43":{
      "scriptId":"u28"},
    "20b3d5d8cafb46bca982b55a93e49934":{
      "scriptId":"u29"},
    "d0527c26cdae465bac7cf885106b58b4":{
      "scriptId":"u30"},
    "b6d9aa714fc94077af0ccb25adb53d8f":{
      "scriptId":"u31"},
    "c2698d84d0f345b0a41f11be98a86e3b":{
      "scriptId":"u32"},
    "d44a76f857bc4579b55bcf507b387be7":{
      "scriptId":"u33"},
    "6448db185e2145299d3387f878db5ecc":{
      "scriptId":"u34"},
    "6282d05fa2364713bb4a73c1274207b1":{
      "scriptId":"u35"},
    "9c9ed62eeb364eec92cceb854965f99f":{
      "scriptId":"u36"},
    "8aa4d0d7dc264a06809871ea1c35da8a":{
      "scriptId":"u37"},
    "61cf3a19041c4ceb9006e31a9958a3bb":{
      "scriptId":"u38"},
    "79787fac6c1f4be486e83d894d5185e1":{
      "scriptId":"u39"},
    "60a9de68d1d3451c92c35eaf724eec5a":{
      "scriptId":"u40"},
    "ff2e931a9a514d9d80ab5fc5dce49d32":{
      "scriptId":"u41"},
    "e14d9000eb6948d6903800b1cb953f47":{
      "scriptId":"u42"},
    "44c3929271f9466ab21dd04ac832bf75":{
      "scriptId":"u43"},
    "9f30df6773af4650b5f8cac5c4109b2b":{
      "scriptId":"u44"},
    "4b9a4c9ea3fc4b1c8c89f7d5f653823c":{
      "scriptId":"u45"},
    "bcb23fbf8924420b86e3f436c039b5d0":{
      "scriptId":"u46"},
    "a73971df86ba4fb1b06063b2a695ecb4":{
      "scriptId":"u47"},
    "0b40acf3e7ae43dfb0f3844ac71b7a3c":{
      "scriptId":"u48"},
    "3d47c3f99e764eafa707ff177b6658c6":{
      "scriptId":"u49"},
    "5f9b45f02a9f436597b6554f951b1643":{
      "scriptId":"u50"},
    "34bd43d8b2c24e54b2b6674d075dc960":{
      "scriptId":"u51"},
    "e969d9e811c646c8804b4cc4b68151bf":{
      "scriptId":"u52"}}});