$axure.loadCurrentPage({
  "url":"cici-pc.html",
  "generationDate":new Date(1456808408645.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8fb05b3933e47098b8d3d2ab8cb71b1",
    "type":"Axure:Page",
    "name":"cici-pc",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dacddefe995746d58d168881932f4c55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-211,
              "y":0},
            "size":{
              "width":1411,
              "height":1235}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f3030edabe433887ff193f6da76e6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-211,
                  "y":0},
                "size":{
                  "width":1411,
                  "height":1235}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u0.jpg"}},
{
          "id":"6a9cbf30b6824541988b60a943625c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":40,
              "y":70},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"446395d59ac340dd8c36806a3f7cf2f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":40,
                  "y":70},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"958f7fc9eed94749bcad13807fe56774",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":58,
              "y":81},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc431ca2be5041f990e69b83a1368520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":81},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c4d6c22b35c416a97b05a8edb2c7680",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":50},
            "size":{
              "width":63,
              "height":10},
            "rotation":"300",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cici-pc/u6_line.png"}},
{
          "id":"5f5c79e6e22146a990dbae094bbc881d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":104},
            "size":{
              "width":229,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2132443678374dd98627e44e48990044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":960,
                  "y":104},
                "size":{
                  "width":229,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b55858323ab04c2d99cdd83e5efbf1a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":488,
              "y":160},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367a6d0f53b943a5a281222f6bfe32b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":488,
                  "y":160},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"aa76b866853b4751920029445424f143",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":506,
              "y":171},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b65d401b964765b9d74ac6d7f2a468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":506,
                  "y":171},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f364014d30b24452a1f19ef84cbbc415",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":220},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ef1cb627044bd1b46f309ba3797624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":220},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"a03367a067a748899c893d01219d9ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":818,
              "y":231},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b3cf40abb14037b614e52a1a1e8c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":818,
                  "y":231},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5039046e91724cedbe44fde696b7853f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":469.5,
              "y":360},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d7ed37da5a4ed29f647ca71035472e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":469.5,
                  "y":360},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"bb2f3cbf5ea140b0821cbe431fe7c940",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":487.5,
              "y":371},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1750b0f99a42476fa7a715212c785a25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":487.5,
                  "y":371},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e666f907c6f44a36bff5b5f5fb7880e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":159},
            "size":{
              "width":288,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb9023ab337497d9ce88434fb59e24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":159},
                "size":{
                  "width":288,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03384789b012449ba24a91393622309b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":490},
            "size":{
              "width":1165,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cici-pc/u23_line.png"}},
{
          "id":"3331c8cc96e840d2a119a31a41c8da69",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":422},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77139ef4c7f24b7a89022ba51ce6f28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":422},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7c340fb5d654a9281bd88efd1234f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":535},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f825067adfd46c883ce73f36dacf3f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":535},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"322705191795428fa428099eb33d73ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":243},
            "size":{
              "width":326,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd61e2856b8a4fd1be79340ec4644816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":243},
                "size":{
                  "width":326,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f9a63b5e4c5466399afa28220398f86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":410,
              "y":535},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5eb30a8b0a94f208f8e22d7741e9e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":410,
                  "y":535},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"db0d472c7917428e9b65fd8ede0ab472",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":428,
              "y":546},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374b4073f66d479db20dec197baca867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":428,
                  "y":546},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"891689f52e6b4c1f9f33d726f95f2700",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":818,
              "y":592.5},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e025b01871d4572a74b6ba31af8586c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":818,
                  "y":592.5},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"d369c38442624dbeb6ef1f698f6452d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":836,
              "y":603.5},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ca4d7a8923429fbdbd4b2dd3c59ef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":603.5},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e8c371cd340489bafc57f3c553bde1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":470,
              "y":750},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"317f17dd40744e2da93c5829de2095a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":470,
                  "y":750},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"82abf973edba4cff8e887594ea085948",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":488,
              "y":762},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96b5bd8e248c4ce196f097d3a1fab4fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":762},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7773e7596b1044ce806d2c5123cb77d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":890},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6fbca24fe364da698d0c1c0d33236c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":170,
                  "y":890},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"b7cb95b58c7c4fa6b6012c35b7c729fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":188,
              "y":902},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c17da4b86c094cdcb1e3e1d42050f79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":188,
                  "y":902},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"485c772671724854b10beae4ac91b170",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":830,
              "y":940},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b864d233a4462c8d5f2f86445fc120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":830,
                  "y":940},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u2.png"}},
{
          "id":"fefa6524ef84413ba756030cd02c1600",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":848,
              "y":952},
            "size":{
              "width":14,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84ead58945454484bce22794fe90aa41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":848,
                  "y":952},
                "size":{
                  "width":14,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88637a58d9884c0db00bcb638afa07da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":964,
              "y":360},
            "size":{
              "width":157,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de708c3521d45bea83988d827a37055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":964,
                  "y":360},
                "size":{
                  "width":157,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79b85c489c4c4fe39c251636c0bb10d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":150,
              "y":584},
            "size":{
              "width":310,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"255edc059f444d5da323f96f4c84fc71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":150,
                  "y":584},
                "size":{
                  "width":310,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cici-pc/u52.png"}},
{
          "id":"74f54f3df411448d8d6fe22c8244056a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":690},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cici-pc/u54_line.png"}},
{
          "id":"4227fd58fcc34ca8bab8e4f0860dce59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":964,
              "y":680},
            "size":{
              "width":211,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d2e74889ed46348857c2eb340e6300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":964,
                  "y":680},
                "size":{
                  "width":211,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81c6d3b72df249e4a4ada1225a9d164a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":660},
            "size":{
              "width":10,
              "height":104},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/cici-pc/u57_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cici-pc/u57_line.png"}},
{
          "id":"d9ed87ba75b240e59f0f3af9cc8259ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":1020},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e28bb0660720443fa283639e50ac6a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":1020},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dacddefe995746d58d168881932f4c55":{
      "scriptId":"u0"},
    "72f3030edabe433887ff193f6da76e6b":{
      "scriptId":"u1"},
    "6a9cbf30b6824541988b60a943625c14":{
      "scriptId":"u2"},
    "446395d59ac340dd8c36806a3f7cf2f3":{
      "scriptId":"u3"},
    "958f7fc9eed94749bcad13807fe56774":{
      "scriptId":"u4"},
    "cc431ca2be5041f990e69b83a1368520":{
      "scriptId":"u5"},
    "4c4d6c22b35c416a97b05a8edb2c7680":{
      "scriptId":"u6"},
    "5f5c79e6e22146a990dbae094bbc881d":{
      "scriptId":"u7"},
    "2132443678374dd98627e44e48990044":{
      "scriptId":"u8"},
    "b55858323ab04c2d99cdd83e5efbf1a8":{
      "scriptId":"u9"},
    "367a6d0f53b943a5a281222f6bfe32b3":{
      "scriptId":"u10"},
    "aa76b866853b4751920029445424f143":{
      "scriptId":"u11"},
    "66b65d401b964765b9d74ac6d7f2a468":{
      "scriptId":"u12"},
    "f364014d30b24452a1f19ef84cbbc415":{
      "scriptId":"u13"},
    "39ef1cb627044bd1b46f309ba3797624":{
      "scriptId":"u14"},
    "a03367a067a748899c893d01219d9ed9":{
      "scriptId":"u15"},
    "28b3cf40abb14037b614e52a1a1e8c71":{
      "scriptId":"u16"},
    "5039046e91724cedbe44fde696b7853f":{
      "scriptId":"u17"},
    "46d7ed37da5a4ed29f647ca71035472e":{
      "scriptId":"u18"},
    "bb2f3cbf5ea140b0821cbe431fe7c940":{
      "scriptId":"u19"},
    "1750b0f99a42476fa7a715212c785a25":{
      "scriptId":"u20"},
    "e666f907c6f44a36bff5b5f5fb7880e9":{
      "scriptId":"u21"},
    "efb9023ab337497d9ce88434fb59e24f":{
      "scriptId":"u22"},
    "03384789b012449ba24a91393622309b":{
      "scriptId":"u23"},
    "3331c8cc96e840d2a119a31a41c8da69":{
      "scriptId":"u24"},
    "77139ef4c7f24b7a89022ba51ce6f28d":{
      "scriptId":"u25"},
    "d7c340fb5d654a9281bd88efd1234f24":{
      "scriptId":"u26"},
    "7f825067adfd46c883ce73f36dacf3f0":{
      "scriptId":"u27"},
    "322705191795428fa428099eb33d73ec":{
      "scriptId":"u28"},
    "cd61e2856b8a4fd1be79340ec4644816":{
      "scriptId":"u29"},
    "4f9a63b5e4c5466399afa28220398f86":{
      "scriptId":"u30"},
    "b5eb30a8b0a94f208f8e22d7741e9e8d":{
      "scriptId":"u31"},
    "db0d472c7917428e9b65fd8ede0ab472":{
      "scriptId":"u32"},
    "374b4073f66d479db20dec197baca867":{
      "scriptId":"u33"},
    "891689f52e6b4c1f9f33d726f95f2700":{
      "scriptId":"u34"},
    "1e025b01871d4572a74b6ba31af8586c":{
      "scriptId":"u35"},
    "d369c38442624dbeb6ef1f698f6452d1":{
      "scriptId":"u36"},
    "48ca4d7a8923429fbdbd4b2dd3c59ef8":{
      "scriptId":"u37"},
    "5e8c371cd340489bafc57f3c553bde1f":{
      "scriptId":"u38"},
    "317f17dd40744e2da93c5829de2095a8":{
      "scriptId":"u39"},
    "82abf973edba4cff8e887594ea085948":{
      "scriptId":"u40"},
    "96b5bd8e248c4ce196f097d3a1fab4fe":{
      "scriptId":"u41"},
    "7773e7596b1044ce806d2c5123cb77d8":{
      "scriptId":"u42"},
    "e6fbca24fe364da698d0c1c0d33236c6":{
      "scriptId":"u43"},
    "b7cb95b58c7c4fa6b6012c35b7c729fa":{
      "scriptId":"u44"},
    "c17da4b86c094cdcb1e3e1d42050f79d":{
      "scriptId":"u45"},
    "485c772671724854b10beae4ac91b170":{
      "scriptId":"u46"},
    "86b864d233a4462c8d5f2f86445fc120":{
      "scriptId":"u47"},
    "fefa6524ef84413ba756030cd02c1600":{
      "scriptId":"u48"},
    "84ead58945454484bce22794fe90aa41":{
      "scriptId":"u49"},
    "88637a58d9884c0db00bcb638afa07da":{
      "scriptId":"u50"},
    "0de708c3521d45bea83988d827a37055":{
      "scriptId":"u51"},
    "79b85c489c4c4fe39c251636c0bb10d4":{
      "scriptId":"u52"},
    "255edc059f444d5da323f96f4c84fc71":{
      "scriptId":"u53"},
    "74f54f3df411448d8d6fe22c8244056a":{
      "scriptId":"u54"},
    "4227fd58fcc34ca8bab8e4f0860dce59":{
      "scriptId":"u55"},
    "e7d2e74889ed46348857c2eb340e6300":{
      "scriptId":"u56"},
    "81c6d3b72df249e4a4ada1225a9d164a":{
      "scriptId":"u57"},
    "d9ed87ba75b240e59f0f3af9cc8259ad":{
      "scriptId":"u58"},
    "e28bb0660720443fa283639e50ac6a23":{
      "scriptId":"u59"}}});